// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: breeding.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.hverse.game.protogen {

  /// <summary>Holder for reflection information generated from breeding.proto</summary>
  public static partial class BreedingReflection {

    #region Descriptor
    /// <summary>File descriptor for breeding.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BreedingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5icmVlZGluZy5wcm90bxoLaG9yc2UucHJvdG8i6AIKD0JyZWVkaW5nTWVz",
            "c2FnZRIlCgdtc2dUeXBlGAEgASgOMhQuQnJlZWRpbmdNZXNzYWdlVHlwZRIx",
            "ChNicmVlZGluZ0luZm9SZXF1ZXN0GAIgASgLMhQuQnJlZWRpbmdJbmZvUmVx",
            "dWVzdBIzChRicmVlZGluZ0luZm9SZXNwb25zZRgDIAEoCzIVLkJyZWVkaW5n",
            "SW5mb1Jlc3BvbnNlEikKD2JyZWVkaW5nUmVxdWVzdBgEIAEoCzIQLkJyZWVk",
            "aW5nUmVxdWVzdBIrChBicmVlZGluZ1Jlc3BvbnNlGAUgASgLMhEuQnJlZWRp",
            "bmdSZXNwb25zZRI1ChVmaW5pc2hCcmVlZGluZ1JlcXVlc3QYBiABKAsyFi5G",
            "aW5pc2hCcmVlZGluZ1JlcXVlc3QSNwoWZmluaXNoQnJlZWRpbmdSZXNwb25z",
            "ZRgHIAEoCzIXLkZpbmlzaEJyZWVkaW5nUmVzcG9uc2UiVgoNQnJlZWRTbG90",
            "SW5mbxINCgVpbmRleBgBIAEoAxIgCgZzdGF0dXMYAiABKA4yEC5CcmVlZFNs",
            "b3RTdGF0dXMSFAoMYnJlZWRpbmdUaW1lGAMgASgDIhUKE0JyZWVkaW5nSW5m",
            "b1JlcXVlc3QiYwoUQnJlZWRpbmdJbmZvUmVzcG9uc2USEQoJZXJyb3JDb2Rl",
            "GAEgASgFEiEKCXNsb3RJbmZvcxgCIAMoCzIOLkJyZWVkU2xvdEluZm8SFQoN",
            "c2xvdE1heE51bWJlchgDIAEoBSJQCg9CcmVlZGluZ1JlcXVlc3QSEQoJc2xv",
            "dEluZGV4GAEgASgFEhMKC21hbGVIb3JzZUlkGAIgASgDEhUKDWZlbWFsZUhv",
            "cnNlSWQYAyABKAMiRwoQQnJlZWRpbmdSZXNwb25zZRIRCgllcnJvckNvZGUY",
            "ASABKAUSIAoIc2xvdEluZm8YAiABKAsyDi5CcmVlZFNsb3RJbmZvIioKFUZp",
            "bmlzaEJyZWVkaW5nUmVxdWVzdBIRCglzbG90SW5kZXgYASABKAUibgoWRmlu",
            "aXNoQnJlZWRpbmdSZXNwb25zZRIRCgllcnJvckNvZGUYASABKAUSIAoIc2xv",
            "dEluZm8YAiABKAsyDi5CcmVlZFNsb3RJbmZvEh8KCmNoaWxkSG9yc2UYAyAB",
            "KAsyCy5Ib3JzZUJhc2ljKrQBChNCcmVlZGluZ01lc3NhZ2VUeXBlEhkKFUJS",
            "RUVESU5HX0lORk9fUkVRVUVTVBAAEhoKFkJSRUVESU5HX0lORk9fUkVTUE9O",
            "U0UQARIUChBCUkVFRElOR19SRVFVRVNUEAISFQoRQlJFRURJTkdfUkVTUE9O",
            "U0UQAxIbChdGSU5JU0hfQlJFRURJTkdfUkVRVUVTVBAEEhwKGEZJTklTSF9C",
            "UkVFRElOR19SRVNQT05TRRAFKjgKD0JyZWVkU2xvdFN0YXR1cxINCglBVkFJ",
            "TEFCTEUQABIMCghCUkVFRElORxABEggKBExPQ0sQAkJLChdpby5odmVyc2Uu",
            "Z2FtZS5wcm90b2dlbkIWQnJlZWRpbmdNZXNzYWdlRmFjdG9yeaoCF2lvLmh2",
            "ZXJzZS5nYW1lLnByb3RvZ2VuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::io.hverse.game.protogen.HorseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::io.hverse.game.protogen.BreedingMessageType), typeof(global::io.hverse.game.protogen.BreedSlotStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedingMessage), global::io.hverse.game.protogen.BreedingMessage.Parser, new[]{ "MsgType", "BreedingInfoRequest", "BreedingInfoResponse", "BreedingRequest", "BreedingResponse", "FinishBreedingRequest", "FinishBreedingResponse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedSlotInfo), global::io.hverse.game.protogen.BreedSlotInfo.Parser, new[]{ "Index", "Status", "BreedingTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedingInfoRequest), global::io.hverse.game.protogen.BreedingInfoRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedingInfoResponse), global::io.hverse.game.protogen.BreedingInfoResponse.Parser, new[]{ "ErrorCode", "SlotInfos", "SlotMaxNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedingRequest), global::io.hverse.game.protogen.BreedingRequest.Parser, new[]{ "SlotIndex", "MaleHorseId", "FemaleHorseId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.BreedingResponse), global::io.hverse.game.protogen.BreedingResponse.Parser, new[]{ "ErrorCode", "SlotInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.FinishBreedingRequest), global::io.hverse.game.protogen.FinishBreedingRequest.Parser, new[]{ "SlotIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.FinishBreedingResponse), global::io.hverse.game.protogen.FinishBreedingResponse.Parser, new[]{ "ErrorCode", "SlotInfo", "ChildHorse" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BreedingMessageType {
    [pbr::OriginalName("BREEDING_INFO_REQUEST")] BreedingInfoRequest = 0,
    [pbr::OriginalName("BREEDING_INFO_RESPONSE")] BreedingInfoResponse = 1,
    [pbr::OriginalName("BREEDING_REQUEST")] BreedingRequest = 2,
    [pbr::OriginalName("BREEDING_RESPONSE")] BreedingResponse = 3,
    [pbr::OriginalName("FINISH_BREEDING_REQUEST")] FinishBreedingRequest = 4,
    [pbr::OriginalName("FINISH_BREEDING_RESPONSE")] FinishBreedingResponse = 5,
  }

  public enum BreedSlotStatus {
    [pbr::OriginalName("AVAILABLE")] Available = 0,
    [pbr::OriginalName("BREEDING")] Breeding = 1,
    [pbr::OriginalName("LOCK")] Lock = 2,
  }

  #endregion

  #region Messages
  public sealed partial class BreedingMessage : pb::IMessage<BreedingMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedingMessage> _parser = new pb::MessageParser<BreedingMessage>(() => new BreedingMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedingMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingMessage(BreedingMessage other) : this() {
      msgType_ = other.msgType_;
      breedingInfoRequest_ = other.breedingInfoRequest_ != null ? other.breedingInfoRequest_.Clone() : null;
      breedingInfoResponse_ = other.breedingInfoResponse_ != null ? other.breedingInfoResponse_.Clone() : null;
      breedingRequest_ = other.breedingRequest_ != null ? other.breedingRequest_.Clone() : null;
      breedingResponse_ = other.breedingResponse_ != null ? other.breedingResponse_.Clone() : null;
      finishBreedingRequest_ = other.finishBreedingRequest_ != null ? other.finishBreedingRequest_.Clone() : null;
      finishBreedingResponse_ = other.finishBreedingResponse_ != null ? other.finishBreedingResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingMessage Clone() {
      return new BreedingMessage(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.BreedingMessageType msgType_ = global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedingMessageType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "breedingInfoRequest" field.</summary>
    public const int BreedingInfoRequestFieldNumber = 2;
    private global::io.hverse.game.protogen.BreedingInfoRequest breedingInfoRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedingInfoRequest BreedingInfoRequest {
      get { return breedingInfoRequest_; }
      set {
        breedingInfoRequest_ = value;
      }
    }

    /// <summary>Field number for the "breedingInfoResponse" field.</summary>
    public const int BreedingInfoResponseFieldNumber = 3;
    private global::io.hverse.game.protogen.BreedingInfoResponse breedingInfoResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedingInfoResponse BreedingInfoResponse {
      get { return breedingInfoResponse_; }
      set {
        breedingInfoResponse_ = value;
      }
    }

    /// <summary>Field number for the "breedingRequest" field.</summary>
    public const int BreedingRequestFieldNumber = 4;
    private global::io.hverse.game.protogen.BreedingRequest breedingRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedingRequest BreedingRequest {
      get { return breedingRequest_; }
      set {
        breedingRequest_ = value;
      }
    }

    /// <summary>Field number for the "breedingResponse" field.</summary>
    public const int BreedingResponseFieldNumber = 5;
    private global::io.hverse.game.protogen.BreedingResponse breedingResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedingResponse BreedingResponse {
      get { return breedingResponse_; }
      set {
        breedingResponse_ = value;
      }
    }

    /// <summary>Field number for the "finishBreedingRequest" field.</summary>
    public const int FinishBreedingRequestFieldNumber = 6;
    private global::io.hverse.game.protogen.FinishBreedingRequest finishBreedingRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.FinishBreedingRequest FinishBreedingRequest {
      get { return finishBreedingRequest_; }
      set {
        finishBreedingRequest_ = value;
      }
    }

    /// <summary>Field number for the "finishBreedingResponse" field.</summary>
    public const int FinishBreedingResponseFieldNumber = 7;
    private global::io.hverse.game.protogen.FinishBreedingResponse finishBreedingResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.FinishBreedingResponse FinishBreedingResponse {
      get { return finishBreedingResponse_; }
      set {
        finishBreedingResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedingMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedingMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (!object.Equals(BreedingInfoRequest, other.BreedingInfoRequest)) return false;
      if (!object.Equals(BreedingInfoResponse, other.BreedingInfoResponse)) return false;
      if (!object.Equals(BreedingRequest, other.BreedingRequest)) return false;
      if (!object.Equals(BreedingResponse, other.BreedingResponse)) return false;
      if (!object.Equals(FinishBreedingRequest, other.FinishBreedingRequest)) return false;
      if (!object.Equals(FinishBreedingResponse, other.FinishBreedingResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest) hash ^= MsgType.GetHashCode();
      if (breedingInfoRequest_ != null) hash ^= BreedingInfoRequest.GetHashCode();
      if (breedingInfoResponse_ != null) hash ^= BreedingInfoResponse.GetHashCode();
      if (breedingRequest_ != null) hash ^= BreedingRequest.GetHashCode();
      if (breedingResponse_ != null) hash ^= BreedingResponse.GetHashCode();
      if (finishBreedingRequest_ != null) hash ^= FinishBreedingRequest.GetHashCode();
      if (finishBreedingResponse_ != null) hash ^= FinishBreedingResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (breedingInfoRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BreedingInfoRequest);
      }
      if (breedingInfoResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BreedingInfoResponse);
      }
      if (breedingRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BreedingRequest);
      }
      if (breedingResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BreedingResponse);
      }
      if (finishBreedingRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(FinishBreedingRequest);
      }
      if (finishBreedingResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(FinishBreedingResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (breedingInfoRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BreedingInfoRequest);
      }
      if (breedingInfoResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BreedingInfoResponse);
      }
      if (breedingRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BreedingRequest);
      }
      if (breedingResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BreedingResponse);
      }
      if (finishBreedingRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(FinishBreedingRequest);
      }
      if (finishBreedingResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(FinishBreedingResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (breedingInfoRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BreedingInfoRequest);
      }
      if (breedingInfoResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BreedingInfoResponse);
      }
      if (breedingRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BreedingRequest);
      }
      if (breedingResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BreedingResponse);
      }
      if (finishBreedingRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FinishBreedingRequest);
      }
      if (finishBreedingResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FinishBreedingResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedingMessage other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::io.hverse.game.protogen.BreedingMessageType.BreedingInfoRequest) {
        MsgType = other.MsgType;
      }
      if (other.breedingInfoRequest_ != null) {
        if (breedingInfoRequest_ == null) {
          BreedingInfoRequest = new global::io.hverse.game.protogen.BreedingInfoRequest();
        }
        BreedingInfoRequest.MergeFrom(other.BreedingInfoRequest);
      }
      if (other.breedingInfoResponse_ != null) {
        if (breedingInfoResponse_ == null) {
          BreedingInfoResponse = new global::io.hverse.game.protogen.BreedingInfoResponse();
        }
        BreedingInfoResponse.MergeFrom(other.BreedingInfoResponse);
      }
      if (other.breedingRequest_ != null) {
        if (breedingRequest_ == null) {
          BreedingRequest = new global::io.hverse.game.protogen.BreedingRequest();
        }
        BreedingRequest.MergeFrom(other.BreedingRequest);
      }
      if (other.breedingResponse_ != null) {
        if (breedingResponse_ == null) {
          BreedingResponse = new global::io.hverse.game.protogen.BreedingResponse();
        }
        BreedingResponse.MergeFrom(other.BreedingResponse);
      }
      if (other.finishBreedingRequest_ != null) {
        if (finishBreedingRequest_ == null) {
          FinishBreedingRequest = new global::io.hverse.game.protogen.FinishBreedingRequest();
        }
        FinishBreedingRequest.MergeFrom(other.FinishBreedingRequest);
      }
      if (other.finishBreedingResponse_ != null) {
        if (finishBreedingResponse_ == null) {
          FinishBreedingResponse = new global::io.hverse.game.protogen.FinishBreedingResponse();
        }
        FinishBreedingResponse.MergeFrom(other.FinishBreedingResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.BreedingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (breedingInfoRequest_ == null) {
              BreedingInfoRequest = new global::io.hverse.game.protogen.BreedingInfoRequest();
            }
            input.ReadMessage(BreedingInfoRequest);
            break;
          }
          case 26: {
            if (breedingInfoResponse_ == null) {
              BreedingInfoResponse = new global::io.hverse.game.protogen.BreedingInfoResponse();
            }
            input.ReadMessage(BreedingInfoResponse);
            break;
          }
          case 34: {
            if (breedingRequest_ == null) {
              BreedingRequest = new global::io.hverse.game.protogen.BreedingRequest();
            }
            input.ReadMessage(BreedingRequest);
            break;
          }
          case 42: {
            if (breedingResponse_ == null) {
              BreedingResponse = new global::io.hverse.game.protogen.BreedingResponse();
            }
            input.ReadMessage(BreedingResponse);
            break;
          }
          case 50: {
            if (finishBreedingRequest_ == null) {
              FinishBreedingRequest = new global::io.hverse.game.protogen.FinishBreedingRequest();
            }
            input.ReadMessage(FinishBreedingRequest);
            break;
          }
          case 58: {
            if (finishBreedingResponse_ == null) {
              FinishBreedingResponse = new global::io.hverse.game.protogen.FinishBreedingResponse();
            }
            input.ReadMessage(FinishBreedingResponse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.BreedingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (breedingInfoRequest_ == null) {
              BreedingInfoRequest = new global::io.hverse.game.protogen.BreedingInfoRequest();
            }
            input.ReadMessage(BreedingInfoRequest);
            break;
          }
          case 26: {
            if (breedingInfoResponse_ == null) {
              BreedingInfoResponse = new global::io.hverse.game.protogen.BreedingInfoResponse();
            }
            input.ReadMessage(BreedingInfoResponse);
            break;
          }
          case 34: {
            if (breedingRequest_ == null) {
              BreedingRequest = new global::io.hverse.game.protogen.BreedingRequest();
            }
            input.ReadMessage(BreedingRequest);
            break;
          }
          case 42: {
            if (breedingResponse_ == null) {
              BreedingResponse = new global::io.hverse.game.protogen.BreedingResponse();
            }
            input.ReadMessage(BreedingResponse);
            break;
          }
          case 50: {
            if (finishBreedingRequest_ == null) {
              FinishBreedingRequest = new global::io.hverse.game.protogen.FinishBreedingRequest();
            }
            input.ReadMessage(FinishBreedingRequest);
            break;
          }
          case 58: {
            if (finishBreedingResponse_ == null) {
              FinishBreedingResponse = new global::io.hverse.game.protogen.FinishBreedingResponse();
            }
            input.ReadMessage(FinishBreedingResponse);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BreedSlotInfo : pb::IMessage<BreedSlotInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedSlotInfo> _parser = new pb::MessageParser<BreedSlotInfo>(() => new BreedSlotInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedSlotInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedSlotInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedSlotInfo(BreedSlotInfo other) : this() {
      index_ = other.index_;
      status_ = other.status_;
      breedingTime_ = other.breedingTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedSlotInfo Clone() {
      return new BreedSlotInfo(this);
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 1;
    private long index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::io.hverse.game.protogen.BreedSlotStatus status_ = global::io.hverse.game.protogen.BreedSlotStatus.Available;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedSlotStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "breedingTime" field.</summary>
    public const int BreedingTimeFieldNumber = 3;
    private long breedingTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BreedingTime {
      get { return breedingTime_; }
      set {
        breedingTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedSlotInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedSlotInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Index != other.Index) return false;
      if (Status != other.Status) return false;
      if (BreedingTime != other.BreedingTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Index != 0L) hash ^= Index.GetHashCode();
      if (Status != global::io.hverse.game.protogen.BreedSlotStatus.Available) hash ^= Status.GetHashCode();
      if (BreedingTime != 0L) hash ^= BreedingTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Index != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Index);
      }
      if (Status != global::io.hverse.game.protogen.BreedSlotStatus.Available) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (BreedingTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BreedingTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Index != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Index);
      }
      if (Status != global::io.hverse.game.protogen.BreedSlotStatus.Available) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (BreedingTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BreedingTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Index != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Index);
      }
      if (Status != global::io.hverse.game.protogen.BreedSlotStatus.Available) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (BreedingTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BreedingTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedSlotInfo other) {
      if (other == null) {
        return;
      }
      if (other.Index != 0L) {
        Index = other.Index;
      }
      if (other.Status != global::io.hverse.game.protogen.BreedSlotStatus.Available) {
        Status = other.Status;
      }
      if (other.BreedingTime != 0L) {
        BreedingTime = other.BreedingTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Index = input.ReadInt64();
            break;
          }
          case 16: {
            Status = (global::io.hverse.game.protogen.BreedSlotStatus) input.ReadEnum();
            break;
          }
          case 24: {
            BreedingTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Index = input.ReadInt64();
            break;
          }
          case 16: {
            Status = (global::io.hverse.game.protogen.BreedSlotStatus) input.ReadEnum();
            break;
          }
          case 24: {
            BreedingTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BreedingInfoRequest : pb::IMessage<BreedingInfoRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedingInfoRequest> _parser = new pb::MessageParser<BreedingInfoRequest>(() => new BreedingInfoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedingInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoRequest(BreedingInfoRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoRequest Clone() {
      return new BreedingInfoRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedingInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedingInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedingInfoRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class BreedingInfoResponse : pb::IMessage<BreedingInfoResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedingInfoResponse> _parser = new pb::MessageParser<BreedingInfoResponse>(() => new BreedingInfoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedingInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoResponse(BreedingInfoResponse other) : this() {
      errorCode_ = other.errorCode_;
      slotInfos_ = other.slotInfos_.Clone();
      slotMaxNumber_ = other.slotMaxNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingInfoResponse Clone() {
      return new BreedingInfoResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private int errorCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "slotInfos" field.</summary>
    public const int SlotInfosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::io.hverse.game.protogen.BreedSlotInfo> _repeated_slotInfos_codec
        = pb::FieldCodec.ForMessage(18, global::io.hverse.game.protogen.BreedSlotInfo.Parser);
    private readonly pbc::RepeatedField<global::io.hverse.game.protogen.BreedSlotInfo> slotInfos_ = new pbc::RepeatedField<global::io.hverse.game.protogen.BreedSlotInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::io.hverse.game.protogen.BreedSlotInfo> SlotInfos {
      get { return slotInfos_; }
    }

    /// <summary>Field number for the "slotMaxNumber" field.</summary>
    public const int SlotMaxNumberFieldNumber = 3;
    private int slotMaxNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SlotMaxNumber {
      get { return slotMaxNumber_; }
      set {
        slotMaxNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedingInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedingInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if(!slotInfos_.Equals(other.slotInfos_)) return false;
      if (SlotMaxNumber != other.SlotMaxNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      hash ^= slotInfos_.GetHashCode();
      if (SlotMaxNumber != 0) hash ^= SlotMaxNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      slotInfos_.WriteTo(output, _repeated_slotInfos_codec);
      if (SlotMaxNumber != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SlotMaxNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      slotInfos_.WriteTo(ref output, _repeated_slotInfos_codec);
      if (SlotMaxNumber != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SlotMaxNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      size += slotInfos_.CalculateSize(_repeated_slotInfos_codec);
      if (SlotMaxNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotMaxNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedingInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      slotInfos_.Add(other.slotInfos_);
      if (other.SlotMaxNumber != 0) {
        SlotMaxNumber = other.SlotMaxNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            slotInfos_.AddEntriesFrom(input, _repeated_slotInfos_codec);
            break;
          }
          case 24: {
            SlotMaxNumber = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            slotInfos_.AddEntriesFrom(ref input, _repeated_slotInfos_codec);
            break;
          }
          case 24: {
            SlotMaxNumber = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BreedingRequest : pb::IMessage<BreedingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedingRequest> _parser = new pb::MessageParser<BreedingRequest>(() => new BreedingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingRequest(BreedingRequest other) : this() {
      slotIndex_ = other.slotIndex_;
      maleHorseId_ = other.maleHorseId_;
      femaleHorseId_ = other.femaleHorseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingRequest Clone() {
      return new BreedingRequest(this);
    }

    /// <summary>Field number for the "slotIndex" field.</summary>
    public const int SlotIndexFieldNumber = 1;
    private int slotIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SlotIndex {
      get { return slotIndex_; }
      set {
        slotIndex_ = value;
      }
    }

    /// <summary>Field number for the "maleHorseId" field.</summary>
    public const int MaleHorseIdFieldNumber = 2;
    private long maleHorseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MaleHorseId {
      get { return maleHorseId_; }
      set {
        maleHorseId_ = value;
      }
    }

    /// <summary>Field number for the "femaleHorseId" field.</summary>
    public const int FemaleHorseIdFieldNumber = 3;
    private long femaleHorseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FemaleHorseId {
      get { return femaleHorseId_; }
      set {
        femaleHorseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SlotIndex != other.SlotIndex) return false;
      if (MaleHorseId != other.MaleHorseId) return false;
      if (FemaleHorseId != other.FemaleHorseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SlotIndex != 0) hash ^= SlotIndex.GetHashCode();
      if (MaleHorseId != 0L) hash ^= MaleHorseId.GetHashCode();
      if (FemaleHorseId != 0L) hash ^= FemaleHorseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SlotIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotIndex);
      }
      if (MaleHorseId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MaleHorseId);
      }
      if (FemaleHorseId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(FemaleHorseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SlotIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotIndex);
      }
      if (MaleHorseId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MaleHorseId);
      }
      if (FemaleHorseId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(FemaleHorseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SlotIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotIndex);
      }
      if (MaleHorseId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MaleHorseId);
      }
      if (FemaleHorseId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FemaleHorseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedingRequest other) {
      if (other == null) {
        return;
      }
      if (other.SlotIndex != 0) {
        SlotIndex = other.SlotIndex;
      }
      if (other.MaleHorseId != 0L) {
        MaleHorseId = other.MaleHorseId;
      }
      if (other.FemaleHorseId != 0L) {
        FemaleHorseId = other.FemaleHorseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SlotIndex = input.ReadInt32();
            break;
          }
          case 16: {
            MaleHorseId = input.ReadInt64();
            break;
          }
          case 24: {
            FemaleHorseId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SlotIndex = input.ReadInt32();
            break;
          }
          case 16: {
            MaleHorseId = input.ReadInt64();
            break;
          }
          case 24: {
            FemaleHorseId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BreedingResponse : pb::IMessage<BreedingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BreedingResponse> _parser = new pb::MessageParser<BreedingResponse>(() => new BreedingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BreedingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingResponse(BreedingResponse other) : this() {
      errorCode_ = other.errorCode_;
      slotInfo_ = other.slotInfo_ != null ? other.slotInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BreedingResponse Clone() {
      return new BreedingResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private int errorCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "slotInfo" field.</summary>
    public const int SlotInfoFieldNumber = 2;
    private global::io.hverse.game.protogen.BreedSlotInfo slotInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedSlotInfo SlotInfo {
      get { return slotInfo_; }
      set {
        slotInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BreedingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BreedingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if (!object.Equals(SlotInfo, other.SlotInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      if (slotInfo_ != null) hash ^= SlotInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (slotInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (slotInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      if (slotInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SlotInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BreedingResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.slotInfo_ != null) {
        if (slotInfo_ == null) {
          SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
        }
        SlotInfo.MergeFrom(other.SlotInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (slotInfo_ == null) {
              SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
            }
            input.ReadMessage(SlotInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (slotInfo_ == null) {
              SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
            }
            input.ReadMessage(SlotInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FinishBreedingRequest : pb::IMessage<FinishBreedingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishBreedingRequest> _parser = new pb::MessageParser<FinishBreedingRequest>(() => new FinishBreedingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishBreedingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingRequest(FinishBreedingRequest other) : this() {
      slotIndex_ = other.slotIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingRequest Clone() {
      return new FinishBreedingRequest(this);
    }

    /// <summary>Field number for the "slotIndex" field.</summary>
    public const int SlotIndexFieldNumber = 1;
    private int slotIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SlotIndex {
      get { return slotIndex_; }
      set {
        slotIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishBreedingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishBreedingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SlotIndex != other.SlotIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SlotIndex != 0) hash ^= SlotIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SlotIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SlotIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SlotIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishBreedingRequest other) {
      if (other == null) {
        return;
      }
      if (other.SlotIndex != 0) {
        SlotIndex = other.SlotIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SlotIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SlotIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FinishBreedingResponse : pb::IMessage<FinishBreedingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishBreedingResponse> _parser = new pb::MessageParser<FinishBreedingResponse>(() => new FinishBreedingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishBreedingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.BreedingReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingResponse(FinishBreedingResponse other) : this() {
      errorCode_ = other.errorCode_;
      slotInfo_ = other.slotInfo_ != null ? other.slotInfo_.Clone() : null;
      childHorse_ = other.childHorse_ != null ? other.childHorse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishBreedingResponse Clone() {
      return new FinishBreedingResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private int errorCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "slotInfo" field.</summary>
    public const int SlotInfoFieldNumber = 2;
    private global::io.hverse.game.protogen.BreedSlotInfo slotInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.BreedSlotInfo SlotInfo {
      get { return slotInfo_; }
      set {
        slotInfo_ = value;
      }
    }

    /// <summary>Field number for the "childHorse" field.</summary>
    public const int ChildHorseFieldNumber = 3;
    private global::io.hverse.game.protogen.HorseBasic childHorse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.HorseBasic ChildHorse {
      get { return childHorse_; }
      set {
        childHorse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishBreedingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishBreedingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if (!object.Equals(SlotInfo, other.SlotInfo)) return false;
      if (!object.Equals(ChildHorse, other.ChildHorse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      if (slotInfo_ != null) hash ^= SlotInfo.GetHashCode();
      if (childHorse_ != null) hash ^= ChildHorse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (slotInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotInfo);
      }
      if (childHorse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ChildHorse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (slotInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotInfo);
      }
      if (childHorse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ChildHorse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      if (slotInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SlotInfo);
      }
      if (childHorse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChildHorse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishBreedingResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.slotInfo_ != null) {
        if (slotInfo_ == null) {
          SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
        }
        SlotInfo.MergeFrom(other.SlotInfo);
      }
      if (other.childHorse_ != null) {
        if (childHorse_ == null) {
          ChildHorse = new global::io.hverse.game.protogen.HorseBasic();
        }
        ChildHorse.MergeFrom(other.ChildHorse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (slotInfo_ == null) {
              SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
            }
            input.ReadMessage(SlotInfo);
            break;
          }
          case 26: {
            if (childHorse_ == null) {
              ChildHorse = new global::io.hverse.game.protogen.HorseBasic();
            }
            input.ReadMessage(ChildHorse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (slotInfo_ == null) {
              SlotInfo = new global::io.hverse.game.protogen.BreedSlotInfo();
            }
            input.ReadMessage(SlotInfo);
            break;
          }
          case 26: {
            if (childHorse_ == null) {
              ChildHorse = new global::io.hverse.game.protogen.HorseBasic();
            }
            input.ReadMessage(ChildHorse);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
