// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.hverse.game.protogen {

  /// <summary>Holder for reflection information generated from chest.proto</summary>
  public static partial class ChestReflection {

    #region Descriptor
    /// <summary>File descriptor for chest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtjaGVzdC5wcm90bxoKZGF0YS5wcm90byLyAgoMQ2hlc3RNZXNzYWdlEiIK",
            "B21zZ1R5cGUYASABKA4yES5DaGVzdE1lc3NhZ2VUeXBlEisKEG9wZW5DaGVz",
            "dFJlcXVlc3QYAiABKAsyES5PcGVuQ2hlc3RSZXF1ZXN0Ei0KEW9wZW5DaGVz",
            "dFJlc3BvbnNlGAMgASgLMhIuT3BlbkNoZXN0UmVzcG9uc2USMwoUY29tYmlu",
            "ZVBpZWNlc1JlcXVlc3QYBCABKAsyFS5Db21iaW5lUGllY2VzUmVxdWVzdBI1",
            "ChVjb21iaW5lUGllY2VzUmVzcG9uc2UYBSABKAsyFi5Db21iaW5lUGllY2Vz",
            "UmVzcG9uc2USOQoXZXhjaGFuZ2VDaGVzdEtleVJlcXVlc3QYBiABKAsyGC5F",
            "eGNoYW5nZUNoZXN0S2V5UmVxdWVzdBI7ChhleGNoYW5nZUNoZXN0S2V5UmVz",
            "cG9uc2UYByABKAsyGS5FeGNoYW5nZUNoZXN0S2V5UmVzcG9uc2UiVgoQT3Bl",
            "bkNoZXN0UmVxdWVzdBIjCgxjaGVzdEtleVR5cGUYASABKA4yDS5DaGVzdEtl",
            "eVR5cGUSHQoJY2hlc3RUeXBlGAIgASgOMgouQ2hlc3RUeXBlIkUKEU9wZW5D",
            "aGVzdFJlc3BvbnNlEhIKCnJlc3VsdENvZGUYASABKAUSHAoHcmV3YXJkcxgC",
            "IAMoCzILLlJld2FyZEluZm8iNQoUQ29tYmluZVBpZWNlc1JlcXVlc3QSHQoJ",
            "cGllY2VUeXBlGAEgASgOMgouUGllY2VUeXBlIisKFUNvbWJpbmVQaWVjZXNS",
            "ZXNwb25zZRISCgpyZXN1bHRDb2RlGAEgASgFIj4KF0V4Y2hhbmdlQ2hlc3RL",
            "ZXlSZXF1ZXN0EiMKDGNoZXN0S2V5VHlwZRgBIAEoDjINLkNoZXN0S2V5VHlw",
            "ZSIuChhFeGNoYW5nZUNoZXN0S2V5UmVzcG9uc2USEgoKcmVzdWx0Q29kZRgB",
            "IAEoBSq9AQoQQ2hlc3RNZXNzYWdlVHlwZRIWChJPUEVOX0NIRVNUX1JFUVVF",
            "U1QQABIXChNPUEVOX0NIRVNUX1JFU1BPTlNFEAESGgoWQ09NQklORV9QSUVD",
            "RVNfUkVRVUVTVBACEhsKF0NPTUJJTkVfUElFQ0VTX1JFU1BPTlNFEAMSHgoa",
            "RVhDSEFOR0VfQ0hFU1RfS0VZX1JFUVVFU1QQBBIfChtFWENIQU5HRV9DSEVT",
            "VF9LRVlfUkVTUE9OU0UQBUJIChdpby5odmVyc2UuZ2FtZS5wcm90b2dlbkIT",
            "Q2hlc3RNZXNzYWdlRmFjdG9yeaoCF2lvLmh2ZXJzZS5nYW1lLnByb3RvZ2Vu",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::io.hverse.game.protogen.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::io.hverse.game.protogen.ChestMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.ChestMessage), global::io.hverse.game.protogen.ChestMessage.Parser, new[]{ "MsgType", "OpenChestRequest", "OpenChestResponse", "CombinePiecesRequest", "CombinePiecesResponse", "ExchangeChestKeyRequest", "ExchangeChestKeyResponse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.OpenChestRequest), global::io.hverse.game.protogen.OpenChestRequest.Parser, new[]{ "ChestKeyType", "ChestType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.OpenChestResponse), global::io.hverse.game.protogen.OpenChestResponse.Parser, new[]{ "ResultCode", "Rewards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.CombinePiecesRequest), global::io.hverse.game.protogen.CombinePiecesRequest.Parser, new[]{ "PieceType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.CombinePiecesResponse), global::io.hverse.game.protogen.CombinePiecesResponse.Parser, new[]{ "ResultCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.ExchangeChestKeyRequest), global::io.hverse.game.protogen.ExchangeChestKeyRequest.Parser, new[]{ "ChestKeyType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.ExchangeChestKeyResponse), global::io.hverse.game.protogen.ExchangeChestKeyResponse.Parser, new[]{ "ResultCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChestMessageType {
    [pbr::OriginalName("OPEN_CHEST_REQUEST")] OpenChestRequest = 0,
    [pbr::OriginalName("OPEN_CHEST_RESPONSE")] OpenChestResponse = 1,
    [pbr::OriginalName("COMBINE_PIECES_REQUEST")] CombinePiecesRequest = 2,
    [pbr::OriginalName("COMBINE_PIECES_RESPONSE")] CombinePiecesResponse = 3,
    [pbr::OriginalName("EXCHANGE_CHEST_KEY_REQUEST")] ExchangeChestKeyRequest = 4,
    [pbr::OriginalName("EXCHANGE_CHEST_KEY_RESPONSE")] ExchangeChestKeyResponse = 5,
  }

  #endregion

  #region Messages
  public sealed partial class ChestMessage : pb::IMessage<ChestMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChestMessage> _parser = new pb::MessageParser<ChestMessage>(() => new ChestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChestMessage(ChestMessage other) : this() {
      msgType_ = other.msgType_;
      openChestRequest_ = other.openChestRequest_ != null ? other.openChestRequest_.Clone() : null;
      openChestResponse_ = other.openChestResponse_ != null ? other.openChestResponse_.Clone() : null;
      combinePiecesRequest_ = other.combinePiecesRequest_ != null ? other.combinePiecesRequest_.Clone() : null;
      combinePiecesResponse_ = other.combinePiecesResponse_ != null ? other.combinePiecesResponse_.Clone() : null;
      exchangeChestKeyRequest_ = other.exchangeChestKeyRequest_ != null ? other.exchangeChestKeyRequest_.Clone() : null;
      exchangeChestKeyResponse_ = other.exchangeChestKeyResponse_ != null ? other.exchangeChestKeyResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChestMessage Clone() {
      return new ChestMessage(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.ChestMessageType msgType_ = global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ChestMessageType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "openChestRequest" field.</summary>
    public const int OpenChestRequestFieldNumber = 2;
    private global::io.hverse.game.protogen.OpenChestRequest openChestRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.OpenChestRequest OpenChestRequest {
      get { return openChestRequest_; }
      set {
        openChestRequest_ = value;
      }
    }

    /// <summary>Field number for the "openChestResponse" field.</summary>
    public const int OpenChestResponseFieldNumber = 3;
    private global::io.hverse.game.protogen.OpenChestResponse openChestResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.OpenChestResponse OpenChestResponse {
      get { return openChestResponse_; }
      set {
        openChestResponse_ = value;
      }
    }

    /// <summary>Field number for the "combinePiecesRequest" field.</summary>
    public const int CombinePiecesRequestFieldNumber = 4;
    private global::io.hverse.game.protogen.CombinePiecesRequest combinePiecesRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.CombinePiecesRequest CombinePiecesRequest {
      get { return combinePiecesRequest_; }
      set {
        combinePiecesRequest_ = value;
      }
    }

    /// <summary>Field number for the "combinePiecesResponse" field.</summary>
    public const int CombinePiecesResponseFieldNumber = 5;
    private global::io.hverse.game.protogen.CombinePiecesResponse combinePiecesResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.CombinePiecesResponse CombinePiecesResponse {
      get { return combinePiecesResponse_; }
      set {
        combinePiecesResponse_ = value;
      }
    }

    /// <summary>Field number for the "exchangeChestKeyRequest" field.</summary>
    public const int ExchangeChestKeyRequestFieldNumber = 6;
    private global::io.hverse.game.protogen.ExchangeChestKeyRequest exchangeChestKeyRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ExchangeChestKeyRequest ExchangeChestKeyRequest {
      get { return exchangeChestKeyRequest_; }
      set {
        exchangeChestKeyRequest_ = value;
      }
    }

    /// <summary>Field number for the "exchangeChestKeyResponse" field.</summary>
    public const int ExchangeChestKeyResponseFieldNumber = 7;
    private global::io.hverse.game.protogen.ExchangeChestKeyResponse exchangeChestKeyResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ExchangeChestKeyResponse ExchangeChestKeyResponse {
      get { return exchangeChestKeyResponse_; }
      set {
        exchangeChestKeyResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (!object.Equals(OpenChestRequest, other.OpenChestRequest)) return false;
      if (!object.Equals(OpenChestResponse, other.OpenChestResponse)) return false;
      if (!object.Equals(CombinePiecesRequest, other.CombinePiecesRequest)) return false;
      if (!object.Equals(CombinePiecesResponse, other.CombinePiecesResponse)) return false;
      if (!object.Equals(ExchangeChestKeyRequest, other.ExchangeChestKeyRequest)) return false;
      if (!object.Equals(ExchangeChestKeyResponse, other.ExchangeChestKeyResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest) hash ^= MsgType.GetHashCode();
      if (openChestRequest_ != null) hash ^= OpenChestRequest.GetHashCode();
      if (openChestResponse_ != null) hash ^= OpenChestResponse.GetHashCode();
      if (combinePiecesRequest_ != null) hash ^= CombinePiecesRequest.GetHashCode();
      if (combinePiecesResponse_ != null) hash ^= CombinePiecesResponse.GetHashCode();
      if (exchangeChestKeyRequest_ != null) hash ^= ExchangeChestKeyRequest.GetHashCode();
      if (exchangeChestKeyResponse_ != null) hash ^= ExchangeChestKeyResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (openChestRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OpenChestRequest);
      }
      if (openChestResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OpenChestResponse);
      }
      if (combinePiecesRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CombinePiecesRequest);
      }
      if (combinePiecesResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CombinePiecesResponse);
      }
      if (exchangeChestKeyRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExchangeChestKeyRequest);
      }
      if (exchangeChestKeyResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ExchangeChestKeyResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (openChestRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OpenChestRequest);
      }
      if (openChestResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OpenChestResponse);
      }
      if (combinePiecesRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CombinePiecesRequest);
      }
      if (combinePiecesResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CombinePiecesResponse);
      }
      if (exchangeChestKeyRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExchangeChestKeyRequest);
      }
      if (exchangeChestKeyResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ExchangeChestKeyResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (openChestRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OpenChestRequest);
      }
      if (openChestResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OpenChestResponse);
      }
      if (combinePiecesRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CombinePiecesRequest);
      }
      if (combinePiecesResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CombinePiecesResponse);
      }
      if (exchangeChestKeyRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExchangeChestKeyRequest);
      }
      if (exchangeChestKeyResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExchangeChestKeyResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChestMessage other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::io.hverse.game.protogen.ChestMessageType.OpenChestRequest) {
        MsgType = other.MsgType;
      }
      if (other.openChestRequest_ != null) {
        if (openChestRequest_ == null) {
          OpenChestRequest = new global::io.hverse.game.protogen.OpenChestRequest();
        }
        OpenChestRequest.MergeFrom(other.OpenChestRequest);
      }
      if (other.openChestResponse_ != null) {
        if (openChestResponse_ == null) {
          OpenChestResponse = new global::io.hverse.game.protogen.OpenChestResponse();
        }
        OpenChestResponse.MergeFrom(other.OpenChestResponse);
      }
      if (other.combinePiecesRequest_ != null) {
        if (combinePiecesRequest_ == null) {
          CombinePiecesRequest = new global::io.hverse.game.protogen.CombinePiecesRequest();
        }
        CombinePiecesRequest.MergeFrom(other.CombinePiecesRequest);
      }
      if (other.combinePiecesResponse_ != null) {
        if (combinePiecesResponse_ == null) {
          CombinePiecesResponse = new global::io.hverse.game.protogen.CombinePiecesResponse();
        }
        CombinePiecesResponse.MergeFrom(other.CombinePiecesResponse);
      }
      if (other.exchangeChestKeyRequest_ != null) {
        if (exchangeChestKeyRequest_ == null) {
          ExchangeChestKeyRequest = new global::io.hverse.game.protogen.ExchangeChestKeyRequest();
        }
        ExchangeChestKeyRequest.MergeFrom(other.ExchangeChestKeyRequest);
      }
      if (other.exchangeChestKeyResponse_ != null) {
        if (exchangeChestKeyResponse_ == null) {
          ExchangeChestKeyResponse = new global::io.hverse.game.protogen.ExchangeChestKeyResponse();
        }
        ExchangeChestKeyResponse.MergeFrom(other.ExchangeChestKeyResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.ChestMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (openChestRequest_ == null) {
              OpenChestRequest = new global::io.hverse.game.protogen.OpenChestRequest();
            }
            input.ReadMessage(OpenChestRequest);
            break;
          }
          case 26: {
            if (openChestResponse_ == null) {
              OpenChestResponse = new global::io.hverse.game.protogen.OpenChestResponse();
            }
            input.ReadMessage(OpenChestResponse);
            break;
          }
          case 34: {
            if (combinePiecesRequest_ == null) {
              CombinePiecesRequest = new global::io.hverse.game.protogen.CombinePiecesRequest();
            }
            input.ReadMessage(CombinePiecesRequest);
            break;
          }
          case 42: {
            if (combinePiecesResponse_ == null) {
              CombinePiecesResponse = new global::io.hverse.game.protogen.CombinePiecesResponse();
            }
            input.ReadMessage(CombinePiecesResponse);
            break;
          }
          case 50: {
            if (exchangeChestKeyRequest_ == null) {
              ExchangeChestKeyRequest = new global::io.hverse.game.protogen.ExchangeChestKeyRequest();
            }
            input.ReadMessage(ExchangeChestKeyRequest);
            break;
          }
          case 58: {
            if (exchangeChestKeyResponse_ == null) {
              ExchangeChestKeyResponse = new global::io.hverse.game.protogen.ExchangeChestKeyResponse();
            }
            input.ReadMessage(ExchangeChestKeyResponse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.ChestMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (openChestRequest_ == null) {
              OpenChestRequest = new global::io.hverse.game.protogen.OpenChestRequest();
            }
            input.ReadMessage(OpenChestRequest);
            break;
          }
          case 26: {
            if (openChestResponse_ == null) {
              OpenChestResponse = new global::io.hverse.game.protogen.OpenChestResponse();
            }
            input.ReadMessage(OpenChestResponse);
            break;
          }
          case 34: {
            if (combinePiecesRequest_ == null) {
              CombinePiecesRequest = new global::io.hverse.game.protogen.CombinePiecesRequest();
            }
            input.ReadMessage(CombinePiecesRequest);
            break;
          }
          case 42: {
            if (combinePiecesResponse_ == null) {
              CombinePiecesResponse = new global::io.hverse.game.protogen.CombinePiecesResponse();
            }
            input.ReadMessage(CombinePiecesResponse);
            break;
          }
          case 50: {
            if (exchangeChestKeyRequest_ == null) {
              ExchangeChestKeyRequest = new global::io.hverse.game.protogen.ExchangeChestKeyRequest();
            }
            input.ReadMessage(ExchangeChestKeyRequest);
            break;
          }
          case 58: {
            if (exchangeChestKeyResponse_ == null) {
              ExchangeChestKeyResponse = new global::io.hverse.game.protogen.ExchangeChestKeyResponse();
            }
            input.ReadMessage(ExchangeChestKeyResponse);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenChestRequest : pb::IMessage<OpenChestRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenChestRequest> _parser = new pb::MessageParser<OpenChestRequest>(() => new OpenChestRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenChestRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestRequest(OpenChestRequest other) : this() {
      chestKeyType_ = other.chestKeyType_;
      chestType_ = other.chestType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestRequest Clone() {
      return new OpenChestRequest(this);
    }

    /// <summary>Field number for the "chestKeyType" field.</summary>
    public const int ChestKeyTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.ChestKeyType chestKeyType_ = global::io.hverse.game.protogen.ChestKeyType.Common;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ChestKeyType ChestKeyType {
      get { return chestKeyType_; }
      set {
        chestKeyType_ = value;
      }
    }

    /// <summary>Field number for the "chestType" field.</summary>
    public const int ChestTypeFieldNumber = 2;
    private global::io.hverse.game.protogen.ChestType chestType_ = global::io.hverse.game.protogen.ChestType.Common;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ChestType ChestType {
      get { return chestType_; }
      set {
        chestType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenChestRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenChestRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChestKeyType != other.ChestKeyType) return false;
      if (ChestType != other.ChestType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) hash ^= ChestKeyType.GetHashCode();
      if (ChestType != global::io.hverse.game.protogen.ChestType.Common) hash ^= ChestType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChestKeyType);
      }
      if (ChestType != global::io.hverse.game.protogen.ChestType.Common) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChestType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChestKeyType);
      }
      if (ChestType != global::io.hverse.game.protogen.ChestType.Common) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChestType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChestKeyType);
      }
      if (ChestType != global::io.hverse.game.protogen.ChestType.Common) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChestType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenChestRequest other) {
      if (other == null) {
        return;
      }
      if (other.ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        ChestKeyType = other.ChestKeyType;
      }
      if (other.ChestType != global::io.hverse.game.protogen.ChestType.Common) {
        ChestType = other.ChestType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChestKeyType = (global::io.hverse.game.protogen.ChestKeyType) input.ReadEnum();
            break;
          }
          case 16: {
            ChestType = (global::io.hverse.game.protogen.ChestType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChestKeyType = (global::io.hverse.game.protogen.ChestKeyType) input.ReadEnum();
            break;
          }
          case 16: {
            ChestType = (global::io.hverse.game.protogen.ChestType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenChestResponse : pb::IMessage<OpenChestResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenChestResponse> _parser = new pb::MessageParser<OpenChestResponse>(() => new OpenChestResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenChestResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestResponse(OpenChestResponse other) : this() {
      resultCode_ = other.resultCode_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenChestResponse Clone() {
      return new OpenChestResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::io.hverse.game.protogen.RewardInfo> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::io.hverse.game.protogen.RewardInfo.Parser);
    private readonly pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> rewards_ = new pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenChestResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenChestResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenChestResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CombinePiecesRequest : pb::IMessage<CombinePiecesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CombinePiecesRequest> _parser = new pb::MessageParser<CombinePiecesRequest>(() => new CombinePiecesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CombinePiecesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesRequest(CombinePiecesRequest other) : this() {
      pieceType_ = other.pieceType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesRequest Clone() {
      return new CombinePiecesRequest(this);
    }

    /// <summary>Field number for the "pieceType" field.</summary>
    public const int PieceTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.PieceType pieceType_ = global::io.hverse.game.protogen.PieceType.Chest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.PieceType PieceType {
      get { return pieceType_; }
      set {
        pieceType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CombinePiecesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CombinePiecesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PieceType != other.PieceType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PieceType != global::io.hverse.game.protogen.PieceType.Chest) hash ^= PieceType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PieceType != global::io.hverse.game.protogen.PieceType.Chest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PieceType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PieceType != global::io.hverse.game.protogen.PieceType.Chest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PieceType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PieceType != global::io.hverse.game.protogen.PieceType.Chest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PieceType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CombinePiecesRequest other) {
      if (other == null) {
        return;
      }
      if (other.PieceType != global::io.hverse.game.protogen.PieceType.Chest) {
        PieceType = other.PieceType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PieceType = (global::io.hverse.game.protogen.PieceType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PieceType = (global::io.hverse.game.protogen.PieceType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CombinePiecesResponse : pb::IMessage<CombinePiecesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CombinePiecesResponse> _parser = new pb::MessageParser<CombinePiecesResponse>(() => new CombinePiecesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CombinePiecesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesResponse(CombinePiecesResponse other) : this() {
      resultCode_ = other.resultCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinePiecesResponse Clone() {
      return new CombinePiecesResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CombinePiecesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CombinePiecesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CombinePiecesResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExchangeChestKeyRequest : pb::IMessage<ExchangeChestKeyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExchangeChestKeyRequest> _parser = new pb::MessageParser<ExchangeChestKeyRequest>(() => new ExchangeChestKeyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExchangeChestKeyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyRequest(ExchangeChestKeyRequest other) : this() {
      chestKeyType_ = other.chestKeyType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyRequest Clone() {
      return new ExchangeChestKeyRequest(this);
    }

    /// <summary>Field number for the "chestKeyType" field.</summary>
    public const int ChestKeyTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.ChestKeyType chestKeyType_ = global::io.hverse.game.protogen.ChestKeyType.Common;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.ChestKeyType ChestKeyType {
      get { return chestKeyType_; }
      set {
        chestKeyType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExchangeChestKeyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExchangeChestKeyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChestKeyType != other.ChestKeyType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) hash ^= ChestKeyType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChestKeyType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChestKeyType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChestKeyType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExchangeChestKeyRequest other) {
      if (other == null) {
        return;
      }
      if (other.ChestKeyType != global::io.hverse.game.protogen.ChestKeyType.Common) {
        ChestKeyType = other.ChestKeyType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChestKeyType = (global::io.hverse.game.protogen.ChestKeyType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChestKeyType = (global::io.hverse.game.protogen.ChestKeyType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExchangeChestKeyResponse : pb::IMessage<ExchangeChestKeyResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExchangeChestKeyResponse> _parser = new pb::MessageParser<ExchangeChestKeyResponse>(() => new ExchangeChestKeyResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExchangeChestKeyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.ChestReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyResponse(ExchangeChestKeyResponse other) : this() {
      resultCode_ = other.resultCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeChestKeyResponse Clone() {
      return new ExchangeChestKeyResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExchangeChestKeyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExchangeChestKeyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExchangeChestKeyResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
