// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.hverse.game.protogen {

  /// <summary>Holder for reflection information generated from data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpkYXRhLnByb3RvIlkKCUhvcnNlSW5mbxINCgVuZnRJZBgBIAEoBRIeCghy",
            "YW5rVHlwZRgCIAEoDjIMLk5mdFJhbmtUeXBlEh0KCWhvcnNlVHlwZRgDIAEo",
            "DjIKLkhvcnNlVHlwZSpYCgtOZnRSYW5rVHlwZRIVChFSQU5LX1RZUEVfVU5L",
            "Tk9XThAAEgUKAUQQARIFCgFDEAISBQoBQhADEgUKAUEQBBIFCgFTEAUSBgoC",
            "U1MQBhIHCgNTU1MQByotCglIb3JzZVR5cGUSCQoFTElHSFQQABILCgdUSFVO",
            "REVSEAESCAoEREFSSxACQkcKF2lvLmh2ZXJzZS5nYW1lLnByb3RvZ2VuQhJE",
            "YXRhTWVzc2FnZUZhY3RvcnmqAhdpby5odmVyc2UuZ2FtZS5wcm90b2dlbmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::io.hverse.game.protogen.NftRankType), typeof(global::io.hverse.game.protogen.HorseType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.HorseInfo), global::io.hverse.game.protogen.HorseInfo.Parser, new[]{ "NftId", "RankType", "HorseType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum NftRankType {
    [pbr::OriginalName("RANK_TYPE_UNKNOWN")] RankTypeUnknown = 0,
    [pbr::OriginalName("D")] D = 1,
    [pbr::OriginalName("C")] C = 2,
    [pbr::OriginalName("B")] B = 3,
    [pbr::OriginalName("A")] A = 4,
    [pbr::OriginalName("S")] S = 5,
    [pbr::OriginalName("SS")] Ss = 6,
    [pbr::OriginalName("SSS")] Sss = 7,
  }

  public enum HorseType {
    [pbr::OriginalName("LIGHT")] Light = 0,
    [pbr::OriginalName("THUNDER")] Thunder = 1,
    [pbr::OriginalName("DARK")] Dark = 2,
  }

  #endregion

  #region Messages
  public sealed partial class HorseInfo : pb::IMessage<HorseInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HorseInfo> _parser = new pb::MessageParser<HorseInfo>(() => new HorseInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HorseInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.DataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HorseInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HorseInfo(HorseInfo other) : this() {
      nftId_ = other.nftId_;
      rankType_ = other.rankType_;
      horseType_ = other.horseType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HorseInfo Clone() {
      return new HorseInfo(this);
    }

    /// <summary>Field number for the "nftId" field.</summary>
    public const int NftIdFieldNumber = 1;
    private int nftId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NftId {
      get { return nftId_; }
      set {
        nftId_ = value;
      }
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 2;
    private global::io.hverse.game.protogen.NftRankType rankType_ = global::io.hverse.game.protogen.NftRankType.RankTypeUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.NftRankType RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "horseType" field.</summary>
    public const int HorseTypeFieldNumber = 3;
    private global::io.hverse.game.protogen.HorseType horseType_ = global::io.hverse.game.protogen.HorseType.Light;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.HorseType HorseType {
      get { return horseType_; }
      set {
        horseType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HorseInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HorseInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NftId != other.NftId) return false;
      if (RankType != other.RankType) return false;
      if (HorseType != other.HorseType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NftId != 0) hash ^= NftId.GetHashCode();
      if (RankType != global::io.hverse.game.protogen.NftRankType.RankTypeUnknown) hash ^= RankType.GetHashCode();
      if (HorseType != global::io.hverse.game.protogen.HorseType.Light) hash ^= HorseType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NftId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NftId);
      }
      if (RankType != global::io.hverse.game.protogen.NftRankType.RankTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) RankType);
      }
      if (HorseType != global::io.hverse.game.protogen.HorseType.Light) {
        output.WriteRawTag(24);
        output.WriteEnum((int) HorseType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NftId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NftId);
      }
      if (RankType != global::io.hverse.game.protogen.NftRankType.RankTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) RankType);
      }
      if (HorseType != global::io.hverse.game.protogen.HorseType.Light) {
        output.WriteRawTag(24);
        output.WriteEnum((int) HorseType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NftId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NftId);
      }
      if (RankType != global::io.hverse.game.protogen.NftRankType.RankTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RankType);
      }
      if (HorseType != global::io.hverse.game.protogen.HorseType.Light) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) HorseType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HorseInfo other) {
      if (other == null) {
        return;
      }
      if (other.NftId != 0) {
        NftId = other.NftId;
      }
      if (other.RankType != global::io.hverse.game.protogen.NftRankType.RankTypeUnknown) {
        RankType = other.RankType;
      }
      if (other.HorseType != global::io.hverse.game.protogen.HorseType.Light) {
        HorseType = other.HorseType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NftId = input.ReadInt32();
            break;
          }
          case 16: {
            RankType = (global::io.hverse.game.protogen.NftRankType) input.ReadEnum();
            break;
          }
          case 24: {
            HorseType = (global::io.hverse.game.protogen.HorseType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NftId = input.ReadInt32();
            break;
          }
          case 16: {
            RankType = (global::io.hverse.game.protogen.NftRankType) input.ReadEnum();
            break;
          }
          case 24: {
            HorseType = (global::io.hverse.game.protogen.HorseType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
