// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: training.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.hverse.game.protogen {

  /// <summary>Holder for reflection information generated from training.proto</summary>
  public static partial class TrainingReflection {

    #region Descriptor
    /// <summary>File descriptor for training.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrainingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg50cmFpbmluZy5wcm90bxoKZGF0YS5wcm90byKsAQoPVHJhaW5pbmdNZXNz",
            "YWdlEiUKB21zZ1R5cGUYASABKA4yFC5UcmFpbmluZ01lc3NhZ2VUeXBlEjcK",
            "FnRyYWluaW5nUmV3YXJkc1JlcXVlc3QYAiABKAsyFy5UcmFpbmluZ1Jld2Fy",
            "ZHNSZXF1ZXN0EjkKF3RyYWluaW5nUmV3YXJkc1Jlc3BvbnNlGAMgASgLMhgu",
            "VHJhaW5pbmdSZXdhcmRzUmVzcG9uc2UiPgoWVHJhaW5pbmdSZXdhcmRzUmVx",
            "dWVzdBISCgpjb2luTnVtYmVyGAEgASgDEhAKCGRpc3RhbmNlGAIgASgDInEK",
            "F1RyYWluaW5nUmV3YXJkc1Jlc3BvbnNlEhIKCnJlc3VsdENvZGUYASABKAUS",
            "DwoHbWVzc2FnZRgCIAEoCRITCgtwb2ludE51bWJlchgDIAEoAxIcCgdyZXdh",
            "cmRzGAQgAygLMgsuUmV3YXJkSW5mbypSChNUcmFpbmluZ01lc3NhZ2VUeXBl",
            "EhwKGFRSQUlOSU5HX1JFV0FSRFNfUkVRVUVTVBAAEh0KGVRSQUlOSU5HX1JF",
            "V0FSRFNfUkVTUE9OU0UQAUJLChdpby5odmVyc2UuZ2FtZS5wcm90b2dlbkIW",
            "VHJhaW5pbmdNZXNzYWdlRmFjdG9yeaoCF2lvLmh2ZXJzZS5nYW1lLnByb3Rv",
            "Z2VuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::io.hverse.game.protogen.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::io.hverse.game.protogen.TrainingMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.TrainingMessage), global::io.hverse.game.protogen.TrainingMessage.Parser, new[]{ "MsgType", "TrainingRewardsRequest", "TrainingRewardsResponse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.TrainingRewardsRequest), global::io.hverse.game.protogen.TrainingRewardsRequest.Parser, new[]{ "CoinNumber", "Distance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.TrainingRewardsResponse), global::io.hverse.game.protogen.TrainingRewardsResponse.Parser, new[]{ "ResultCode", "Message", "PointNumber", "Rewards" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TrainingMessageType {
    [pbr::OriginalName("TRAINING_REWARDS_REQUEST")] TrainingRewardsRequest = 0,
    [pbr::OriginalName("TRAINING_REWARDS_RESPONSE")] TrainingRewardsResponse = 1,
  }

  #endregion

  #region Messages
  public sealed partial class TrainingMessage : pb::IMessage<TrainingMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainingMessage> _parser = new pb::MessageParser<TrainingMessage>(() => new TrainingMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainingMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage(TrainingMessage other) : this() {
      msgType_ = other.msgType_;
      trainingRewardsRequest_ = other.trainingRewardsRequest_ != null ? other.trainingRewardsRequest_.Clone() : null;
      trainingRewardsResponse_ = other.trainingRewardsResponse_ != null ? other.trainingRewardsResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage Clone() {
      return new TrainingMessage(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.TrainingMessageType msgType_ = global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.TrainingMessageType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "trainingRewardsRequest" field.</summary>
    public const int TrainingRewardsRequestFieldNumber = 2;
    private global::io.hverse.game.protogen.TrainingRewardsRequest trainingRewardsRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.TrainingRewardsRequest TrainingRewardsRequest {
      get { return trainingRewardsRequest_; }
      set {
        trainingRewardsRequest_ = value;
      }
    }

    /// <summary>Field number for the "trainingRewardsResponse" field.</summary>
    public const int TrainingRewardsResponseFieldNumber = 3;
    private global::io.hverse.game.protogen.TrainingRewardsResponse trainingRewardsResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.TrainingRewardsResponse TrainingRewardsResponse {
      get { return trainingRewardsResponse_; }
      set {
        trainingRewardsResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainingMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainingMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (!object.Equals(TrainingRewardsRequest, other.TrainingRewardsRequest)) return false;
      if (!object.Equals(TrainingRewardsResponse, other.TrainingRewardsResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest) hash ^= MsgType.GetHashCode();
      if (trainingRewardsRequest_ != null) hash ^= TrainingRewardsRequest.GetHashCode();
      if (trainingRewardsResponse_ != null) hash ^= TrainingRewardsResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (trainingRewardsRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrainingRewardsRequest);
      }
      if (trainingRewardsResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrainingRewardsResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (trainingRewardsRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrainingRewardsRequest);
      }
      if (trainingRewardsResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrainingRewardsResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (trainingRewardsRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrainingRewardsRequest);
      }
      if (trainingRewardsResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrainingRewardsResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainingMessage other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::io.hverse.game.protogen.TrainingMessageType.TrainingRewardsRequest) {
        MsgType = other.MsgType;
      }
      if (other.trainingRewardsRequest_ != null) {
        if (trainingRewardsRequest_ == null) {
          TrainingRewardsRequest = new global::io.hverse.game.protogen.TrainingRewardsRequest();
        }
        TrainingRewardsRequest.MergeFrom(other.TrainingRewardsRequest);
      }
      if (other.trainingRewardsResponse_ != null) {
        if (trainingRewardsResponse_ == null) {
          TrainingRewardsResponse = new global::io.hverse.game.protogen.TrainingRewardsResponse();
        }
        TrainingRewardsResponse.MergeFrom(other.TrainingRewardsResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.TrainingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (trainingRewardsRequest_ == null) {
              TrainingRewardsRequest = new global::io.hverse.game.protogen.TrainingRewardsRequest();
            }
            input.ReadMessage(TrainingRewardsRequest);
            break;
          }
          case 26: {
            if (trainingRewardsResponse_ == null) {
              TrainingRewardsResponse = new global::io.hverse.game.protogen.TrainingRewardsResponse();
            }
            input.ReadMessage(TrainingRewardsResponse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.TrainingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (trainingRewardsRequest_ == null) {
              TrainingRewardsRequest = new global::io.hverse.game.protogen.TrainingRewardsRequest();
            }
            input.ReadMessage(TrainingRewardsRequest);
            break;
          }
          case 26: {
            if (trainingRewardsResponse_ == null) {
              TrainingRewardsResponse = new global::io.hverse.game.protogen.TrainingRewardsResponse();
            }
            input.ReadMessage(TrainingRewardsResponse);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TrainingRewardsRequest : pb::IMessage<TrainingRewardsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainingRewardsRequest> _parser = new pb::MessageParser<TrainingRewardsRequest>(() => new TrainingRewardsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainingRewardsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsRequest(TrainingRewardsRequest other) : this() {
      coinNumber_ = other.coinNumber_;
      distance_ = other.distance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsRequest Clone() {
      return new TrainingRewardsRequest(this);
    }

    /// <summary>Field number for the "coinNumber" field.</summary>
    public const int CoinNumberFieldNumber = 1;
    private long coinNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CoinNumber {
      get { return coinNumber_; }
      set {
        coinNumber_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 2;
    private long distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainingRewardsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainingRewardsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CoinNumber != other.CoinNumber) return false;
      if (Distance != other.Distance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CoinNumber != 0L) hash ^= CoinNumber.GetHashCode();
      if (Distance != 0L) hash ^= Distance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CoinNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CoinNumber);
      }
      if (Distance != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CoinNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CoinNumber);
      }
      if (Distance != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CoinNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CoinNumber);
      }
      if (Distance != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Distance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainingRewardsRequest other) {
      if (other == null) {
        return;
      }
      if (other.CoinNumber != 0L) {
        CoinNumber = other.CoinNumber;
      }
      if (other.Distance != 0L) {
        Distance = other.Distance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CoinNumber = input.ReadInt64();
            break;
          }
          case 16: {
            Distance = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CoinNumber = input.ReadInt64();
            break;
          }
          case 16: {
            Distance = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TrainingRewardsResponse : pb::IMessage<TrainingRewardsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainingRewardsResponse> _parser = new pb::MessageParser<TrainingRewardsResponse>(() => new TrainingRewardsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainingRewardsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsResponse(TrainingRewardsResponse other) : this() {
      resultCode_ = other.resultCode_;
      message_ = other.message_;
      pointNumber_ = other.pointNumber_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingRewardsResponse Clone() {
      return new TrainingRewardsResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pointNumber" field.</summary>
    public const int PointNumberFieldNumber = 3;
    private long pointNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PointNumber {
      get { return pointNumber_; }
      set {
        pointNumber_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::io.hverse.game.protogen.RewardInfo> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(34, global::io.hverse.game.protogen.RewardInfo.Parser);
    private readonly pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> rewards_ = new pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainingRewardsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainingRewardsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (Message != other.Message) return false;
      if (PointNumber != other.PointNumber) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (PointNumber != 0L) hash ^= PointNumber.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (PointNumber != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PointNumber);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (PointNumber != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PointNumber);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (PointNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PointNumber);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainingRewardsResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.PointNumber != 0L) {
        PointNumber = other.PointNumber;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            PointNumber = input.ReadInt64();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            PointNumber = input.ReadInt64();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
