// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: training.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.hverse.game.protogen {

  /// <summary>Holder for reflection information generated from training.proto</summary>
  public static partial class TrainingReflection {

    #region Descriptor
    /// <summary>File descriptor for training.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrainingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg50cmFpbmluZy5wcm90bxoKZGF0YS5wcm90byKUAgoPVHJhaW5pbmdNZXNz",
            "YWdlEiUKB21zZ1R5cGUYASABKA4yFC5UcmFpbmluZ01lc3NhZ2VUeXBlEjMK",
            "FHN0YXJ0VHJhaW5pbmdSZXF1ZXN0GAIgASgLMhUuU3RhcnRUcmFpbmluZ1Jl",
            "cXVlc3QSNQoVc3RhcnRUcmFpbmluZ1Jlc3BvbnNlGAMgASgLMhYuU3RhcnRU",
            "cmFpbmluZ1Jlc3BvbnNlEjUKFWZpbmlzaFRyYWluaW5nUmVxdWVzdBgEIAEo",
            "CzIWLkZpbmlzaFRyYWluaW5nUmVxdWVzdBI3ChZmaW5pc2hUcmFpbmluZ1Jl",
            "c3BvbnNlGAUgASgLMhcuRmluaXNoVHJhaW5pbmdSZXNwb25zZSInChRTdGFy",
            "dFRyYWluaW5nUmVxdWVzdBIPCgdob3JzZUlkGAEgASgDIk8KFVN0YXJ0VHJh",
            "aW5pbmdSZXNwb25zZRISCgpyZXN1bHRDb2RlGAEgASgFEg8KB21lc3NhZ2UY",
            "AiABKAkSEQoJaGFwcGluZXNzGAMgASgFIj0KFUZpbmlzaFRyYWluaW5nUmVx",
            "dWVzdBISCgpjb2luTnVtYmVyGAEgASgDEhAKCGRpc3RhbmNlGAIgASgDImoK",
            "FkZpbmlzaFRyYWluaW5nUmVzcG9uc2USEgoKcmVzdWx0Q29kZRgBIAEoBRIP",
            "CgdtZXNzYWdlGAIgASgJEg0KBXNjb3JlGAMgASgDEhwKB3Jld2FyZHMYBCAD",
            "KAsyCy5SZXdhcmRJbmZvKokBChNUcmFpbmluZ01lc3NhZ2VUeXBlEhoKFlNU",
            "QVJUX1RSQUlOSU5HX1JFUVVFU1QQABIbChdTVEFSVF9UUkFJTklOR19SRVNQ",
            "T05TRRABEhsKF0ZJTklTSF9UUkFJTklOR19SRVFVRVNUEAISHAoYRklOSVNI",
            "X1RSQUlOSU5HX1JFU1BPTlNFEANCSwoXaW8uaHZlcnNlLmdhbWUucHJvdG9n",
            "ZW5CFlRyYWluaW5nTWVzc2FnZUZhY3RvcnmqAhdpby5odmVyc2UuZ2FtZS5w",
            "cm90b2dlbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::io.hverse.game.protogen.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::io.hverse.game.protogen.TrainingMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.TrainingMessage), global::io.hverse.game.protogen.TrainingMessage.Parser, new[]{ "MsgType", "StartTrainingRequest", "StartTrainingResponse", "FinishTrainingRequest", "FinishTrainingResponse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.StartTrainingRequest), global::io.hverse.game.protogen.StartTrainingRequest.Parser, new[]{ "HorseId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.StartTrainingResponse), global::io.hverse.game.protogen.StartTrainingResponse.Parser, new[]{ "ResultCode", "Message", "Happiness" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.FinishTrainingRequest), global::io.hverse.game.protogen.FinishTrainingRequest.Parser, new[]{ "CoinNumber", "Distance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::io.hverse.game.protogen.FinishTrainingResponse), global::io.hverse.game.protogen.FinishTrainingResponse.Parser, new[]{ "ResultCode", "Message", "Score", "Rewards" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TrainingMessageType {
    [pbr::OriginalName("START_TRAINING_REQUEST")] StartTrainingRequest = 0,
    [pbr::OriginalName("START_TRAINING_RESPONSE")] StartTrainingResponse = 1,
    [pbr::OriginalName("FINISH_TRAINING_REQUEST")] FinishTrainingRequest = 2,
    [pbr::OriginalName("FINISH_TRAINING_RESPONSE")] FinishTrainingResponse = 3,
  }

  #endregion

  #region Messages
  public sealed partial class TrainingMessage : pb::IMessage<TrainingMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainingMessage> _parser = new pb::MessageParser<TrainingMessage>(() => new TrainingMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainingMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage(TrainingMessage other) : this() {
      msgType_ = other.msgType_;
      startTrainingRequest_ = other.startTrainingRequest_ != null ? other.startTrainingRequest_.Clone() : null;
      startTrainingResponse_ = other.startTrainingResponse_ != null ? other.startTrainingResponse_.Clone() : null;
      finishTrainingRequest_ = other.finishTrainingRequest_ != null ? other.finishTrainingRequest_.Clone() : null;
      finishTrainingResponse_ = other.finishTrainingResponse_ != null ? other.finishTrainingResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainingMessage Clone() {
      return new TrainingMessage(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::io.hverse.game.protogen.TrainingMessageType msgType_ = global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.TrainingMessageType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "startTrainingRequest" field.</summary>
    public const int StartTrainingRequestFieldNumber = 2;
    private global::io.hverse.game.protogen.StartTrainingRequest startTrainingRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.StartTrainingRequest StartTrainingRequest {
      get { return startTrainingRequest_; }
      set {
        startTrainingRequest_ = value;
      }
    }

    /// <summary>Field number for the "startTrainingResponse" field.</summary>
    public const int StartTrainingResponseFieldNumber = 3;
    private global::io.hverse.game.protogen.StartTrainingResponse startTrainingResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.StartTrainingResponse StartTrainingResponse {
      get { return startTrainingResponse_; }
      set {
        startTrainingResponse_ = value;
      }
    }

    /// <summary>Field number for the "finishTrainingRequest" field.</summary>
    public const int FinishTrainingRequestFieldNumber = 4;
    private global::io.hverse.game.protogen.FinishTrainingRequest finishTrainingRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.FinishTrainingRequest FinishTrainingRequest {
      get { return finishTrainingRequest_; }
      set {
        finishTrainingRequest_ = value;
      }
    }

    /// <summary>Field number for the "finishTrainingResponse" field.</summary>
    public const int FinishTrainingResponseFieldNumber = 5;
    private global::io.hverse.game.protogen.FinishTrainingResponse finishTrainingResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::io.hverse.game.protogen.FinishTrainingResponse FinishTrainingResponse {
      get { return finishTrainingResponse_; }
      set {
        finishTrainingResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainingMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainingMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (!object.Equals(StartTrainingRequest, other.StartTrainingRequest)) return false;
      if (!object.Equals(StartTrainingResponse, other.StartTrainingResponse)) return false;
      if (!object.Equals(FinishTrainingRequest, other.FinishTrainingRequest)) return false;
      if (!object.Equals(FinishTrainingResponse, other.FinishTrainingResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest) hash ^= MsgType.GetHashCode();
      if (startTrainingRequest_ != null) hash ^= StartTrainingRequest.GetHashCode();
      if (startTrainingResponse_ != null) hash ^= StartTrainingResponse.GetHashCode();
      if (finishTrainingRequest_ != null) hash ^= FinishTrainingRequest.GetHashCode();
      if (finishTrainingResponse_ != null) hash ^= FinishTrainingResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (startTrainingRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StartTrainingRequest);
      }
      if (startTrainingResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(StartTrainingResponse);
      }
      if (finishTrainingRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FinishTrainingRequest);
      }
      if (finishTrainingResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(FinishTrainingResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (startTrainingRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StartTrainingRequest);
      }
      if (startTrainingResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(StartTrainingResponse);
      }
      if (finishTrainingRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FinishTrainingRequest);
      }
      if (finishTrainingResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(FinishTrainingResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (startTrainingRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartTrainingRequest);
      }
      if (startTrainingResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartTrainingResponse);
      }
      if (finishTrainingRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FinishTrainingRequest);
      }
      if (finishTrainingResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FinishTrainingResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainingMessage other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::io.hverse.game.protogen.TrainingMessageType.StartTrainingRequest) {
        MsgType = other.MsgType;
      }
      if (other.startTrainingRequest_ != null) {
        if (startTrainingRequest_ == null) {
          StartTrainingRequest = new global::io.hverse.game.protogen.StartTrainingRequest();
        }
        StartTrainingRequest.MergeFrom(other.StartTrainingRequest);
      }
      if (other.startTrainingResponse_ != null) {
        if (startTrainingResponse_ == null) {
          StartTrainingResponse = new global::io.hverse.game.protogen.StartTrainingResponse();
        }
        StartTrainingResponse.MergeFrom(other.StartTrainingResponse);
      }
      if (other.finishTrainingRequest_ != null) {
        if (finishTrainingRequest_ == null) {
          FinishTrainingRequest = new global::io.hverse.game.protogen.FinishTrainingRequest();
        }
        FinishTrainingRequest.MergeFrom(other.FinishTrainingRequest);
      }
      if (other.finishTrainingResponse_ != null) {
        if (finishTrainingResponse_ == null) {
          FinishTrainingResponse = new global::io.hverse.game.protogen.FinishTrainingResponse();
        }
        FinishTrainingResponse.MergeFrom(other.FinishTrainingResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.TrainingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (startTrainingRequest_ == null) {
              StartTrainingRequest = new global::io.hverse.game.protogen.StartTrainingRequest();
            }
            input.ReadMessage(StartTrainingRequest);
            break;
          }
          case 26: {
            if (startTrainingResponse_ == null) {
              StartTrainingResponse = new global::io.hverse.game.protogen.StartTrainingResponse();
            }
            input.ReadMessage(StartTrainingResponse);
            break;
          }
          case 34: {
            if (finishTrainingRequest_ == null) {
              FinishTrainingRequest = new global::io.hverse.game.protogen.FinishTrainingRequest();
            }
            input.ReadMessage(FinishTrainingRequest);
            break;
          }
          case 42: {
            if (finishTrainingResponse_ == null) {
              FinishTrainingResponse = new global::io.hverse.game.protogen.FinishTrainingResponse();
            }
            input.ReadMessage(FinishTrainingResponse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::io.hverse.game.protogen.TrainingMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (startTrainingRequest_ == null) {
              StartTrainingRequest = new global::io.hverse.game.protogen.StartTrainingRequest();
            }
            input.ReadMessage(StartTrainingRequest);
            break;
          }
          case 26: {
            if (startTrainingResponse_ == null) {
              StartTrainingResponse = new global::io.hverse.game.protogen.StartTrainingResponse();
            }
            input.ReadMessage(StartTrainingResponse);
            break;
          }
          case 34: {
            if (finishTrainingRequest_ == null) {
              FinishTrainingRequest = new global::io.hverse.game.protogen.FinishTrainingRequest();
            }
            input.ReadMessage(FinishTrainingRequest);
            break;
          }
          case 42: {
            if (finishTrainingResponse_ == null) {
              FinishTrainingResponse = new global::io.hverse.game.protogen.FinishTrainingResponse();
            }
            input.ReadMessage(FinishTrainingResponse);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StartTrainingRequest : pb::IMessage<StartTrainingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartTrainingRequest> _parser = new pb::MessageParser<StartTrainingRequest>(() => new StartTrainingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StartTrainingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingRequest(StartTrainingRequest other) : this() {
      horseId_ = other.horseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingRequest Clone() {
      return new StartTrainingRequest(this);
    }

    /// <summary>Field number for the "horseId" field.</summary>
    public const int HorseIdFieldNumber = 1;
    private long horseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HorseId {
      get { return horseId_; }
      set {
        horseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StartTrainingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StartTrainingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HorseId != other.HorseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HorseId != 0L) hash ^= HorseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HorseId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(HorseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HorseId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(HorseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HorseId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HorseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StartTrainingRequest other) {
      if (other == null) {
        return;
      }
      if (other.HorseId != 0L) {
        HorseId = other.HorseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HorseId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HorseId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StartTrainingResponse : pb::IMessage<StartTrainingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartTrainingResponse> _parser = new pb::MessageParser<StartTrainingResponse>(() => new StartTrainingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StartTrainingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingResponse(StartTrainingResponse other) : this() {
      resultCode_ = other.resultCode_;
      message_ = other.message_;
      happiness_ = other.happiness_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartTrainingResponse Clone() {
      return new StartTrainingResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "happiness" field.</summary>
    public const int HappinessFieldNumber = 3;
    private int happiness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Happiness {
      get { return happiness_; }
      set {
        happiness_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StartTrainingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StartTrainingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (Message != other.Message) return false;
      if (Happiness != other.Happiness) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Happiness != 0) hash ^= Happiness.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Happiness != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Happiness);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Happiness != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Happiness);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Happiness != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Happiness);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StartTrainingResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Happiness != 0) {
        Happiness = other.Happiness;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Happiness = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Happiness = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FinishTrainingRequest : pb::IMessage<FinishTrainingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishTrainingRequest> _parser = new pb::MessageParser<FinishTrainingRequest>(() => new FinishTrainingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishTrainingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingRequest(FinishTrainingRequest other) : this() {
      coinNumber_ = other.coinNumber_;
      distance_ = other.distance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingRequest Clone() {
      return new FinishTrainingRequest(this);
    }

    /// <summary>Field number for the "coinNumber" field.</summary>
    public const int CoinNumberFieldNumber = 1;
    private long coinNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CoinNumber {
      get { return coinNumber_; }
      set {
        coinNumber_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 2;
    private long distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishTrainingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishTrainingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CoinNumber != other.CoinNumber) return false;
      if (Distance != other.Distance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CoinNumber != 0L) hash ^= CoinNumber.GetHashCode();
      if (Distance != 0L) hash ^= Distance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CoinNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CoinNumber);
      }
      if (Distance != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CoinNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CoinNumber);
      }
      if (Distance != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CoinNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CoinNumber);
      }
      if (Distance != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Distance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishTrainingRequest other) {
      if (other == null) {
        return;
      }
      if (other.CoinNumber != 0L) {
        CoinNumber = other.CoinNumber;
      }
      if (other.Distance != 0L) {
        Distance = other.Distance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CoinNumber = input.ReadInt64();
            break;
          }
          case 16: {
            Distance = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CoinNumber = input.ReadInt64();
            break;
          }
          case 16: {
            Distance = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FinishTrainingResponse : pb::IMessage<FinishTrainingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishTrainingResponse> _parser = new pb::MessageParser<FinishTrainingResponse>(() => new FinishTrainingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishTrainingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::io.hverse.game.protogen.TrainingReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingResponse(FinishTrainingResponse other) : this() {
      resultCode_ = other.resultCode_;
      message_ = other.message_;
      score_ = other.score_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishTrainingResponse Clone() {
      return new FinishTrainingResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 3;
    private long score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::io.hverse.game.protogen.RewardInfo> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(34, global::io.hverse.game.protogen.RewardInfo.Parser);
    private readonly pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> rewards_ = new pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::io.hverse.game.protogen.RewardInfo> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishTrainingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishTrainingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (Message != other.Message) return false;
      if (Score != other.Score) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Score != 0L) hash ^= Score.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Score != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Score);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Score != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Score);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Score != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Score);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishTrainingResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Score != 0L) {
        Score = other.Score;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Score = input.ReadInt64();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Score = input.ReadInt64();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
